---

- name: Gather certificate state
  ansible.builtin.include_tasks: gather.yml
  tags: [always]

- name: Certificate generation
  ansible.builtin.include_tasks: generate.yml
  tags: [generate]

- name: Certificate renewal
  ansible.builtin.include_tasks: renew.yml
  tags: [renew]
