---

- name: "restart apache"
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  become: true
  listen: "restart apache"
  tags:
    - crl_app_config
    - handlers

- name: "restart haproxy"
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
  become: true
  listen: "restart haproxy"
  tags:
    - crl_app_config
    - handlers

- name: "restart rsyslog"
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
  become: true
  listen: "restart rsyslog"
  tags:
    - crl_app_config
    - handlers

- name: "restart etcd"
  ansible.builtin.systemd:
    name: etcd
    state: restarted
  become: true
  listen: "restart etcd"
  tags:
    - crl_app_config
    - handlers

- name: "restart freeradius"
  ansible.builtin.systemd:
    name: freeradius
    state: restarted
  become: true
  listen: "restart freeradius"
  tags:
    - crl_app_config
    - handlers