---

- name: "restart crl-consumer timer"
  ansible.builtin.systemd:
    name: "{{ crl_consumer_timer_name }}.timer"
    state: restarted
  become: true
  listen: "restart crl-consumer"
  tags:
    - crl_consumer
    - handlers

- name: "reload crl-consumer timer"
  ansible.builtin.systemd:
    name: "{{ crl_consumer_timer_name }}.timer"
    daemon_reload: true
    state: started
    enabled: true
  become: true
  listen: "reload crl-consumer"
  tags:
    - crl_consumer
    - handlers