---

- name: "restart apache"
  ansible.builtin.systemd:
    name: "{{ apache_service_name }}"
    state: restarted
  become: true
  listen: "restart apache"
  tags:
    - apache_crl
    - handlers

- name: "reload apache"
  ansible.builtin.systemd:
    name: "{{ apache_service_name }}"
    state: reloaded
  become: true
  listen: "reload apache"
  tags:
    - apache_crl
    - handlers